version: '3'
services:
  app:
    image: mdboard
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./mdboard_data:/data
    environment:
      SECRET: "CHANGETHISLINETOSOMETHINGLONGANDRANDOM"
      ENABLE_HTTPS: "False"
    restart: unless-stopped
