version: '3.5'
services:
  app:
    image: mdboard
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
    environment:
      SECRET: "CHANGETHISLINETOSOMETHINGLONGANDRANDOM"=
